updated bamboo spec

diff --git a/bamboo-specs/bamboo.yaml b/bamboo-specs/bamboo.yaml
--- a/bamboo-specs/bamboo.yaml
+++ b/bamboo-specs/bamboo.yaml
@@ -1,6 +1,6 @@
 
 # ------------------------------------------------------------------------------------------------
-#bamboo plan for running unit tests and doing a release
+#bamboo plan for running unit tests and doing an ORCA code release
 ---
 version: 2
 plan:
@@ -28,7 +28,6 @@ stages:
     manual: true
     final: false
     jobs:
-    - Release ORCA Documentation
     - Release ORCA Code
 
 Set Pending Github Status:
@@ -171,32 +170,6 @@ Report Status:
         ./bin/set_status.sh success ${bamboo.resultsUrl} "Build Success"
       description: Report Success to GitHub
 
-Release ORCA Documentation:
-  key: ROD
-  description: Releases ORCA Documentation to nasa.github.io/cumulus-orca
-  docker:
-    image: maven.earthdata.nasa.gov/cumulus_orca
-    volumes:
-      ${bamboo.working.directory}: ${bamboo.working.directory}
-      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
-  tasks:
-  - checkout:
-      force-clean-build: 'true'
-      path: source
-      description: Checkout Default Repository
-  - script:
-      interpreter: SHELL
-      scripts:
-      - |-
-        #!/bin/bash
-        cd source
-        set -ex
-        if [ ! -f "bin/create_release_documentation.sh" ]; then
-          echo "ERROR: create_release_documentation.sh script does not exist!"
-          exit 1
-        fi
-        bin/create_release_documentation.sh
-      description: Run documentation release script
 Release ORCA Code:
   key: RO
   description: Cleans, creates a GitHub Release and uploads artifacts for release
@@ -254,6 +227,87 @@ branches:
 version: 2
 plan:
   key: ORCA-OI
+plan-permissions:
+- users:
+  - bhazuka
+  - andrew.dorn
+  - rizbi.hassan
+  - scott.saxon
+
+  permissions:
+  - view
+  - edit
+  - build
+  - clone
+  - admin
+...
+
+# ------------------------------------------------------------------------------------------------
+#bamboo plan for doing an ORCA documentation release
+---
+version: 2
+plan:
+  project-key: ORCA
+  key: ORD
+  name: ORCA Release Documentation
+stages:
+- Release Stage:
+    manual: true
+    final: false
+    jobs:
+    - Release ORCA Code
+
+Release ORCA Documentation:
+  key: ROD
+  description: Releases ORCA Documentation to nasa.github.io/cumulus-orca
+  docker:
+    image: maven.earthdata.nasa.gov/cumulus_orca
+    volumes:
+      ${bamboo.working.directory}: ${bamboo.working.directory}
+      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
+  tasks:
+  - checkout:
+      force-clean-build: 'true'
+      path: source
+      description: Checkout Default Repository
+  - script:
+      interpreter: SHELL
+      scripts:
+      - |-
+        #!/bin/bash
+        cd source
+        set -ex
+        if [ ! -f "bin/create_release_documentation.sh" ]; then
+          echo "ERROR: create_release_documentation.sh script does not exist!"
+          exit 1
+        fi
+        bin/create_release_documentation.sh
+      description: Run documentation release script
+
+variables:
+  ORCA_VERSION: 4.0.3
+  RELEASE_FLAG: 'false'
+  REPORT_BUILD_STATUS: 'true'
+  SECRET_GITHUB_EMAIL: BAMSCRT@0@0@HYUkicwfEqt17JZaZuGYmtmRHrnDySiT+kQkBQa7/Rg7IQgl1lUvbncMUu0Wx2k1ayHojNkh2TdOlF0kJ5tw6Q== #encrypted
+  SECRET_GITHUB_TOKEN: BAMSCRT@0@0@nPxyXQXMyE6zm3B1oI8Goma78s0H1fJD4vHy6+dpBQJpjDI2ekbcvCAOI8AyjYiILPhqi2w4fT0fx9MFVXxz2JPTp5uPNzG3GM/8XSUgvYo= #encrypted
+  SECRET_GITHUB_USER: BAMSCRT@0@0@fFtitNITDsAjJqK2ZXjhnBZ96z2775QLzGR1Xz557gSl8HxxBaTD3Fbmp+HUbpfx  #encrypted
+ 
+repositories:
+- orca-develop:
+    scope: global
+triggers:
+- polling: # Does not actually poll, as we do not have webhooks enabled.
+    period: '60' #time in seconds
+branches:
+  create: for-new-branch
+  delete:
+    after-deleted-days: 7
+    after-inactive-days: 30
+  link-to-jira: true
+---
+version: 2
+plan:
+  key: ORCA-ORD
 plan-permissions:
 - users:
   - bhazuka
