removed some stages for testing

diff --git a/bamboo-specs/bamboo.yaml b/bamboo-specs/bamboo.yaml
--- a/bamboo-specs/bamboo.yaml
+++ b/bamboo-specs/bamboo.yaml
@@ -55,74 +55,74 @@ Set Pending Github Status:
         set -ex
         ./bin/set_status.sh pending ${bamboo.resultsUrl} "CI Running"
       description: Set Pending Status
-Build and Test:
-  key: JOB1
-  other:
-    clean-working-dir: true
-  docker:
-    image: amazonlinux:2
-    volumes:
-      ${bamboo.working.directory}: ${bamboo.working.directory}
-      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
-  tasks:
-  - checkout:
-      force-clean-build: 'false'
-      description: checkout code
-  - script:
-      interpreter: SHELL
-      scripts:
-      - |-
-        #!/bin/bash
-        export NODE_VERSION "12.x"
-        export TERRAFORM_VERSION "0.13.6"
+# Build and Test:
+#   key: JOB1
+#   other:
+#     clean-working-dir: true
+#   docker:
+#     image: amazonlinux:2
+#     volumes:
+#       ${bamboo.working.directory}: ${bamboo.working.directory}
+#       ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
+#   tasks:
+#   - checkout:
+#       force-clean-build: 'false'
+#       description: checkout code
+#   - script:
+#       interpreter: SHELL
+#       scripts:
+#       - |-
+#         #!/bin/bash
+#         export NODE_VERSION "12.x"
+#         export TERRAFORM_VERSION "0.13.6"
 
-        # Add NodeJS and Yarn repos & update package index
-        curl -sL https://rpm.nodesource.com/setup_${NODE_VERSION} | bash - 
-        curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
-        yum update -y
+#         # Add NodeJS and Yarn repos & update package index
+#         curl -sL https://rpm.nodesource.com/setup_${NODE_VERSION} | bash - 
+#         curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
+#         yum update -y
 
-        # CLI utilities
-        yum install -y gcc git make openssl unzip wget zip
+#         # CLI utilities
+#         yum install -y gcc git make openssl unzip wget zip
 
-        # Python 3 & NodeJS
-        yum install -y python3-devel
-        yum install -y nodejs yarn
+#         # Python 3 & NodeJS
+#         yum install -y python3-devel
+#         yum install -y nodejs yarn
 
-        # AWS & Terraform
-        yum install -y awscli
-        wget "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
-        unzip *.zip
-        chmod +x terraform
-        mv terraform /usr/local/bin
+#         # AWS & Terraform
+#         yum install -y awscli
+#         wget "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
+#         unzip *.zip
+#         chmod +x terraform
+#         mv terraform /usr/local/bin
 
-        # SSM SessionManager plugin
-        curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm" -o "session-manager-plugin.rpm"
-        yum install -y session-manager-plugin.rpm
-        bin/run_tests.sh
-      description: run all tests
-  - script:
-      interpreter: SHELL
-      scripts:
-      - |-
-        #!/bin/bash
-        ## This script creates a file as a method of letting cleanup jobs know if it was reached, this allows github failure notifications to be sent if the job failed. 
-        set -e
-        touch success.flag
-      description: Set Success Flag
-  final-tasks:
-  - script:
-      interpreter: SHELL
-      scripts:
-      - |-
-        #!/bin/bash
-        ## This script looks for the output from the "Set job success flag" script and reports failure to github if it is not present
-        set -e
+#         # SSM SessionManager plugin
+#         curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm" -o "session-manager-plugin.rpm"
+#         yum install -y session-manager-plugin.rpm
+#         bin/run_tests.sh
+#       description: run all tests
+#   - script:
+#       interpreter: SHELL
+#       scripts:
+#       - |-
+#         #!/bin/bash
+#         ## This script creates a file as a method of letting cleanup jobs know if it was reached, this allows github failure notifications to be sent if the job failed. 
+#         set -e
+#         touch success.flag
+#       description: Set Success Flag
+#   final-tasks:
+#   - script:
+#       interpreter: SHELL
+#       scripts:
+#       - |-
+#         #!/bin/bash
+#         ## This script looks for the output from the "Set job success flag" script and reports failure to github if it is not present
+#         set -e
 
-        if [[ ! -f success.flag ]]; then 
-          echo "Job failed, sending failure notice to github"
-          ./bin/set_status.sh failure ${bamboo.resultsUrl} "Testing Step Failed"
-        fi
-      description: report failure to github
+#         if [[ ! -f success.flag ]]; then 
+#           echo "Job failed, sending failure notice to github"
+#           ./bin/set_status.sh failure ${bamboo.resultsUrl} "Testing Step Failed"
+#         fi
+#       description: report failure to github
 Python snyk:
   key: PS
   other:
